export const BAIRROS_RIO_GRANDE: string[] = [
    "América",
    "Bolaxa",
    "Carreiros",
    "Cassino",
    "Castelo Branco",
    "Centro",
    "Cidade de Águeda",
    "Cidade Nova",
    "COHAB I",
    "COHAB II",
    "COHAB IV",
    "Distrito Domingos Petroline",
    "Frederico Ernesto Buchholz",
    "Getúlio Vargas",
    "Hidráulica",
    "Lagoa",
    "Lar Gaúcho",
    "Miguel de Castro Moreira",
    "Nossa Senhora dos Navegantes",
    "Parque Marinha",
    "Parque Residencial Coelho",
    "Parque Residencial Jardim do Sol",
    "Parque Residencial Salgado Filho",
    "Parque Residencial São Pedro",
    "Povo Novo",
    "Profilurbi",
    "Quinta",
    "Santa Rita de Cássia",
    "São Paulo",
    "Senandes",
    "Vila Bernardeth",
    "Vila Junção",
    "Vila Maria",
    "Vila Maria José",
    "Vila Militar",
    "Vila Nossa Senhora de Fátima",
    "Vila Rural",
    "Vila Santa Rosa",
    "Vila Santa Tereza",
    "Vila São João",
    "Vila São Jorge",
    "Vila São Miguel",
    "Zona Portuária",
    "Distrito Ilha dos Marinheiros",
    "Distrito Povo Novo",
    "Distrito Quinta",
    "Distrito Taim",
    "Bolacha",
    "Cassino (localidade)",
    "Domingos Petroline",
    "Ilha da Torotama",
    "Sítio Santa Cruz",
]